/// Base class for any event generated by a window.
///
/// It is really simple by itself, only containing a [timestamp] representing
/// when the event was generated. As such, [DateTime.now()] should usually be passed
/// to it.
///
/// To receive this kind of event you'll need to add a [WindowEventHandler] when creating
/// the [LiveWindowEntry] instance.
abstract class WindowEvent {
  /// The time when the event was generated. Usually should be [DateTime.now()].
  final DateTime timestamp;

  /// Const constructor for subclasses. Only windows should instantiate an event.
  const WindowEvent({required this.timestamp});
}
